[homebrew]
  taps = []

  brews = [
    "git",
    "vim",
    "tmux",
    "dockutil",
    "pyenv",
    "rbenv",
    "ruby-build",
    "node",
  ]

  casks = [
    # Browsers & Dev Tools
    "google-chrome",
    "iterm2",
    "visual-studio-code",
    "docker",
    "postman",

    # Productivity
    "rectangle",
    "caffeine",
    "spark",
    "productive",

    # Communication & Collaboration
    "slack",
    "zoom",
    "whatsapp",

    # Microsoft Office
    "microsoft-teams",
    "microsoft-word",
    "microsoft-excel",

    # Creative & Design
    "figma",

    # AI
    "chatgpt",
    "claude",

    # Entertainment and Personal
    "discord",
    "spotify",
    "steam",
    "todoist",

    # Security & Privacy
    "1password",
    "nordvpn",
  ]
